import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import getServerTheme from "@/hooks/use-server-dark-mode";
import { CookiesProvider } from "react-cookie";
import LayoutBody from "@/components/layout-body";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const theme = await getServerTheme()
  return (
    <html
      lang="en" className={theme === 'dark' ? 'dark' : ''}
    >
      <LayoutBody>
        {children}
      </LayoutBody>
     
    </html>
  );
}
